version: 2
jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                name: Create virtualenv
                command: python -m venv venv
            - run:
                name: install  requirements
                command: |
                    source venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: creating db
                command: |
                    source venv/bin/activate
                    pip install -r requirements.txt
                    python recreate_db.py
    test:
        working_directory: ~/project
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                name: Create virtualenv
                command: python -m venv venv
            - run:
                name: install  requirements
                command: |
                    source venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Run test
                command: |
                source venv/bin/activate
                pytest -s